version: '2'
services:
  api:
   build: .
   volumes: 
    - ./server:/usr/src/app
    - /usr/src/app/node_modules/
   ports: [ '8006:8006' ]
   links: [ mongo ]
  mongo:
   image: mongo
   ports: [ '27017:27017' ]